LD = g++

NAME = ra

OBJ_DIR = obj
SRC_DIR = ../src
VND_DIR = ../vendor
INC_DIR = ../../include/$(NAME)
LIB_DIR = ../../lib/$(MODULE)
EXC_DIR = ../bin

I_CMD = $(addprefix -I, $(SRC_DIR))
I_CMD_V = $(addprefix -I, $(VND_DIR))
L_CMD = $(addprefix -L, )

CXX_FLAGS = $(I_CMD) $(I_CMD_V) -std=c++0x -Wall -fopenmp
LD_FLAGS = $(I_CMD) $(I_CMD_V) $(L_CMD) -pthread -lstdc++ -fopenmp

API = $(addprefix $(SRC_DIR)/, AfgRead.hpp AfgOverlap.hpp CommonHeaders.hpp Contig.hpp \
      DovetailOverlap.hpp \
      EnhancedSuffixArray.hpp IO.hpp \
      EdgesSet.hpp MhapOverlap.hpp MhapParser.hpp \
	    Overlap.hpp OverlapFunctions.hpp PartialOrderAlignment.hpp Preprocess.hpp ra.hpp Read.hpp ReadIndex.hpp \
	    StringGraph.hpp Utils.hpp)

SRC = $(shell find $(SRC_DIR) -type f -regex ".*\.cpp")
VND = $(shell find $(VND_DIR) -type f -regex ".*\.cpp")
OBJ = $(subst $(SRC_DIR), $(OBJ_DIR), $(addsuffix .o, $(basename $(SRC))))
OBJ += $(subst $(VND_DIR), $(OBJ_DIR), $(addsuffix .o, $(basename $(VND))))
DEP = $(OBJ:.o=.d)
INC = $(subst $(SRC_DIR), $(INC_DIR), $(API))
LIB = $(LIB_DIR)/lib$(NAME).a
EXC = $(NAME)
BIN = $(EXC_DIR)/$(EXC)

all: $(OBJ) include lib

install: bin include lib

bin: $(BIN)

include: $(INC)

lib: $(LIB)

$(EXC): $(OBJ)
	@echo [LD] $@
	@mkdir -p $(dir $@)
	@$(LD) -o $@ $^ $(LD_FLAGS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@echo [CXX] $<
	@mkdir -p $(dir $@)
	@$(CXX) $< -c -o $@ -MMD $(CXX_FLAGS)

$(OBJ_DIR)/%.o: $(VND_DIR)/%.cpp
	@echo [CXX] $<
	@mkdir -p $(dir $@)
	@$(CXX) $< -c -o $@ -MMD $(CXX_FLAGS)

$(INC_DIR)/%.hpp: $(SRC_DIR)/%.hpp
	@echo [CXX] $@
	@mkdir -p $(dir $@)
	@cp $< $@

$(LIB): $(OBJ)
	@echo [AR] $@
	@mkdir -p $(dir $@)
	@ar rcs $(LIB) $(OBJ)

$(BIN): $(EXC)
	@echo [CXX] $@
	@mkdir -p $(dir $@)
	@cp $< $@

clean:
	@echo [RM] cleaning
	@rm $(OBJ_DIR) $(EXC) -rf

remove:
	@echo [RM] removing
	@rm $(INC_DIR) $(LIB) $(BIN) $(EXC) -rf

-include $(DEP)
